In [3]:
import os
os.chdir('D:\Kashishkashyap\iris ml model')


In [4]:
os.getcwd()

'D:\\Kashishkashyap\\iris ml model'

In [5]:
import pandas as pd
import numpy as np

In [6]:
dataset=pd.read_csv('Iris.csv')

In [7]:
dataset

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [12]:
x=dataset.iloc[:,1:5].values

In [13]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [14]:
y=dataset.iloc[:,5].values

In [15]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [16]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)

In [17]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [39]:
# now we apply different models in it

In [40]:
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

LogisticRegression()

In [41]:
y_pred=logmodel.predict(x_test)

In [42]:
y_pred

array([0, 1, 1, 1, 2, 2, 0, 0, 2, 2, 2, 1, 2, 0, 2, 0, 0, 0, 0, 2, 0, 1,
       1, 1, 1, 0, 1, 0, 2, 2])

In [43]:
y_test

array([0, 1, 1, 1, 2, 2, 0, 0, 2, 2, 2, 1, 2, 0, 2, 0, 0, 0, 0, 2, 0, 1,
       2, 2, 1, 0, 1, 0, 2, 2])

In [44]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[11,  0,  0],
       [ 0,  7,  0],
       [ 0,  2, 10]], dtype=int64)

In [46]:
28/30

0.9333333333333333

In [47]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier_knn.fit(x_train,y_train)

KNeighborsClassifier()

In [48]:
y_pred=classifier_knn.predict(x_test)

In [49]:
confusion_matrix(y_test,y_pred)

array([[11,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 11]], dtype=int64)

In [50]:
29/30

0.9666666666666667

In [51]:
from sklearn.naive_bayes import GaussianNB
classifier_nb=GaussianNB()
classifier_nb.fit(x_train,y_train)

GaussianNB()

In [52]:
y_pred=classifier_nb.predict(x_test)

In [54]:
confusion_matrix(y_test,y_pred)

array([[11,  0,  0],
       [ 0,  7,  0],
       [ 0,  2, 10]], dtype=int64)

In [55]:
28/30

0.9333333333333333

In [56]:
from sklearn.svm import SVC
classifier_svm_sigmoid=SVC(kernel='sigmoid')
classifier_svm_sigmoid.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [57]:
y_pred=classifier_svm_sigmoid.predict(x_test)

In [58]:
confusion_matrix(y_test,y_pred)

array([[ 0, 11,  0],
       [ 0,  7,  0],
       [ 0, 12,  0]], dtype=int64)

In [59]:
7/30


0.23333333333333334

In [60]:
from sklearn.svm import SVC
classifier_svm_linear=SVC(kernel='linear')
classifier_svm_linear.fit(x_train,y_train)

SVC(kernel='linear')

In [61]:
y_pred=classifier_svm_linear.predict(x_test)

In [62]:
confusion_matrix(y_test,y_pred)

array([[11,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 11]], dtype=int64)

In [63]:
29/30

0.9666666666666667

In [64]:
from sklearn.svm import SVC
classifier_svm_rbf=SVC(kernel='rbf')
classifier_svm_rbf.fit(x_train,y_train)

SVC()

In [67]:
y_pred=classifier_svm_rbf.predict(x_test)

In [66]:
confusion_matrix(y_test,y_pred)

array([[11,  0,  0],
       [ 0,  7,  0],
       [ 0,  2, 10]], dtype=int64)

In [68]:
from sklearn.svm import SVC
classifier_svm_poly=SVC(kernel='poly')
classifier_svm_poly.fit(x_train,y_train)

SVC(kernel='poly')

In [69]:
y_pred=classifier_svm_poly.predict(x_test)

In [70]:
confusion_matrix(y_test,y_pred)

array([[11,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 11]], dtype=int64)

In [71]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt=DecisionTreeClassifier(criterion='entropy')
classifier_dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [72]:
y_pred=classifier_dt.predict(x_test)

In [73]:
confusion_matrix(y_test,y_pred)

array([[11,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 11]], dtype=int64)

In [74]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf=RandomForestClassifier(n_estimators=3, criterion='entropy')
classifier_rf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [75]:
y_pred=classifier_rf.predict(x_test)

In [76]:
confusion_matrix(y_test,y_pred)

array([[11,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 11]], dtype=int64)